"""empty message

Revision ID: 0dcfe2abd9d3
Revises: a02bf28033b9
Create Date: 2021-12-27 23:53:57.805173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dcfe2abd9d3'
down_revision = 'a02bf28033b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('names', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['useru.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_set',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['questionary.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('quest_id', 'set_id')
    )
    op.add_column('questionary', sa.Column('category', sa.String(length=140), nullable=True))
    op.drop_constraint('questionary_user_fkey', 'questionary', type_='foreignkey')
    op.drop_column('questionary', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionary', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questionary_user_fkey', 'questionary', 'useru', ['user'], ['id'])
    op.drop_column('questionary', 'category')
    op.drop_table('quest_set')
    op.drop_table('set')
    # ### end Alembic commands ###
