"""empty message

Revision ID: 629b4b7976b5
Revises: 0dcfe2abd9d3
Create Date: 2021-12-28 23:42:07.883337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629b4b7976b5'
down_revision = '0dcfe2abd9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_quest',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questionary.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_quest')
    op.drop_table('category')
    # ### end Alembic commands ###
