"""empty message

Revision ID: 65a300cc26c7
Revises: 782fb2a1e816
Create Date: 2021-12-25 11:27:03.488697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65a300cc26c7'
down_revision = '782fb2a1e816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('useru_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['useru_id'], ['useru.id'], ),
    sa.PrimaryKeyConstraint('useru_id', 'interview_id')
    )
    op.add_column('interview', sa.Column('users', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'users')
    op.drop_table('association')
    # ### end Alembic commands ###
