"""empty message

Revision ID: 782fb2a1e816
Revises: e77b6bc50fcb
Create Date: 2021-12-25 11:03:43.491932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782fb2a1e816'
down_revision = 'e77b6bc50fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('useru_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['useru_id'], ['useru.id'], ),
    sa.PrimaryKeyConstraint('useru_id', 'interview_id')
    )
    op.add_column('interview', sa.Column('users', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_foreign_key(None, 'interview', 'useru', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'users')
    op.drop_table('association')
    # ### end Alembic commands ###
