"""empty message

Revision ID: 7e08cd19802d
Revises: 
Create Date: 2021-12-24 23:58:13.367281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e08cd19802d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('users', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_constraint('interview_user_fkey', 'interview', type_='foreignkey')
    op.create_foreign_key(None, 'interview', 'useru', ['users'], ['id'])
    op.drop_column('interview', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_foreign_key('interview_user_fkey', 'interview', 'useru', ['user'], ['id'])
    op.drop_column('interview', 'users')
    # ### end Alembic commands ###
