"""empty message

Revision ID: e77b6bc50fcb
Revises: 7e08cd19802d
Create Date: 2021-12-25 00:18:39.645358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77b6bc50fcb'
down_revision = '7e08cd19802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_user_fkey', 'interview', type_='foreignkey')
    op.drop_column('interview', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('interview_user_fkey', 'interview', 'useru', ['user'], ['id'])
    # ### end Alembic commands ###
